SENSITIVITY=360/65536

HEADER_TO_BYTES = (b'\r',b'\n',b'~')
HEADER = b'\r\n~'

DORIENT = 'DORIENT'
DORIENT_FORMAT = '>HHHHHHHHH'
DORIENT_ID = 112

SETFIL = 'SETFIL'
SETFIL_FORMAT = '>H'
SETFIL_ANS_FORMAT = '>cccBBBH'
SETFIL_ID = 113
SETFIL_COUNT = 3